
- name: copy cert file to pbxware path
  copy: src=../templates/{{ item }} dest={{ asterisk_cert_dir }} mode=0755

  with_items:
    - asterisk.pem
    - ca.crt
  
- name: copy cert file to Nginx Path
  copy: src=../templates/{{ item }} dest={{ nginx_cert_dir }} mode=0755

  with_items:
    - nginx.key
    - nginx.crt
- name: Run command stop nginx  (with 'args' keyword).
  command: /opt/pbxware/sh/nginx -s stop

- name: Run command start nginx  (with 'args' keyword).
  command: /opt/pbxware/sh/nginx 
   
