
- name: copy cert file tp pbxware path
  copy: src=../templates/{{ item }} dest={{ asterisk_cert_dir }} mode=0755

  with_items:
    - asterisk.pem
    - ca.crt
  copy: src=../templates/{{ item }} dest={{ nginx_cert_dir }} mode=0755

  with_items:
    - nginx.key
    - nginx.crt
  notify:
    - /opt/pbxware/sh/nginx -s stop
    
   
