---
- name: get file stat of local files
  stat:
    path: "{{ item.src }}"
  register: project_files_local
  with_items: "{{ project_files.files }}"
  when:
    - project_files.files | length > 0

- name: Ensure files are present on the Target
  copy:
    force: "{{ item.0.force }}"
    src: "{{ item.0.src }}"
    dest: "{{ item.0.dst }}"
    mode: "{{ item.0.mode }}"
  when:
    - project_files_local | length > 0
    - item.1.stat.exists
  with_together:
    - "{{ project_files.files }}"
    - "{{ project_files_local.results }}"

- name: Ensure the templated files are present on the target
  template:
    force: "{{ item.0.force }}"
    src: "{{ item.0.src }}"
    dest: "{{ item.0.dst }}"
    mode: "{{ item.0.mode }}"
  with_together:
    - "{{ project_files.templates }}"
    